{% set name = "optree" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c011c6124d6dcbfceade2d7c4f836eab66ed8cf9ab12f94535b41a71dd734637

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:                    # [win]
    - CMAKE_GENERATOR_PLATFORM=  # [win]
    - CMAKE_GENERATOR=Ninja      # [win]
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.18  # to support `CMAKE_GENERATOR`
    - make                                # [not win]
    - ninja  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - pybind11 2
  run:
    - python
    - typing-extensions >=4.5.0

test:
  imports:
    - optree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  description: Optimized PyTree Utilities.
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
