{% set name = "optree" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c011c6124d6dcbfceade2d7c4f836eab66ed8cf9ab12f94535b41a71dd734637
  # Download the github source because of a missing tests/helpers.py file in the sdist
  - url: https://github.com/metaopt/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 904fc4f5ca53512e65347c8f31b0dda292c4a24530de4e227e6202c94ddfcfe3
    folder: gh

build:
  number: 0
  skip: True  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:             # [win]
    - CMAKE_GENERATOR=Visual Studio 16 2019 # [win]
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.18  # to support `CMAKE_GENERATOR`
    - make                                # [not win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - pybind11 >=2.12
  run:
    - python
    - typing-extensions >=4.5.0

test:
  imports:
    - optree
  source_files:
    - tests
    - gh/tests/helpers.py
  requires:
    - pip
    - pytest
    - pytest-xdist
  commands:
    - pip check
    - cp gh/tests/helpers.py tests
    # test_treespec_pickle_missing_registration fails with AssertionError, see https://github.com/metaopt/optree/issues/199
    - pytest tests -v -k "not test_treespec_pickle_missing_registration"

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  description: Optimized PyTree Utilities.
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
