{% set name = "optree" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/metaopt/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 84b7e203b6e7196df76f4e651eaa3bc6ce0f30495facf434fea850eb4b92279d

build:
  number: 0
  script_env: 
    - _GLIBCXX_USE_CXX11_ABI=1
    # Unset `CMAKE_GENERATOR` and let Visual Studio set to its default
    - CMAKE_GENERATOR=  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make  # [not win]
  host:
    - pip
    - python
    - wheel
    - setuptools >=77.0
    - pybind11 >=2.12
  run:
    - python
    - typing-extensions >=4.6.0  # [py<313]
    - typing-extensions >=4.12.0  # [py>=313]

test:
  source_files:
    - tests
  imports:
    - optree
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pytest-xdist
  

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  description: Optimized PyTree Utilities.
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
